Loading datasets...
Restoring previous...
Epoch 1/300
Train set...
  0%|[35m                                                                            [39m| 0/5322 [00:00<?, ?it/s]
torch.Size([1, 3, 129, 161, 129])
torch.Size([1, 3, 129, 161, 129])
  0%|[35m                                                                            [39m| 0/5322 [01:08<?, ?it/s]
Traceback (most recent call last):
  File "/home/tbarba/projects/MultiModalBrainSurvival/src/autoencoder/train_ae.py", line 245, in <module>
    main(**config)
  File "/home/tbarba/projects/MultiModalBrainSurvival/src/autoencoder/train_ae.py", line 209, in main
    train_epoch_metrics = train_loop(
  File "/home/tbarba/projects/MultiModalBrainSurvival/src/autoencoder/train_ae.py", line 52, in train_loop
    ssimloss = ssim_func(images, outputs[0], data_range=images.max())
  File "/labs/gevaertlab/users/thomas/miniconda/envs/multimodal/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/labs/gevaertlab/users/thomas/miniconda/envs/multimodal/lib/python3.9/site-packages/monai/losses/ssim_loss.py", line 95, in forward
    [
  File "/labs/gevaertlab/users/thomas/miniconda/envs/multimodal/lib/python3.9/site-packages/monai/losses/ssim_loss.py", line 96, in <listcomp>
    SSIMLoss(self.win_size, self.k1, self.k2, self.spatial_dims)(
  File "/labs/gevaertlab/users/thomas/miniconda/envs/multimodal/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/labs/gevaertlab/users/thomas/miniconda/envs/multimodal/lib/python3.9/site-packages/monai/losses/ssim_loss.py", line 116, in forward
    uxy = conv(x * y, w)  # mu_xy
RuntimeError: The size of tensor a (149) must match the size of tensor b (129) at non-singleton dimension 4